//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _LeahyHealthProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public int userid { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string BloodLevel { get; set; }
    }
}
